// <auto-generated />
namespace ExpedienteIDON.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addMunicipioAndEstadoTables1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMunicipioAndEstadoTables1));
        
        string IMigrationMetadata.Id
        {
            get { return "202105071857339_addMunicipioAndEstadoTables1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
